[package]
name = "poek"
version = "0.1.0"
authors = ["Kristoffer Søholm <k.soeholm@gmail.com>"]

[[bin]]
name = "peek"
path = "src/bin/peek.rs"

[[bin]]
name = "poke"
path = "src/bin/poke.rs"

[dependencies]
mio = "0.5"
bytes = "0.3.0"
